import type { ExperienceConfig } from '../theme-config';

export const bioluminescent: ExperienceConfig = {
  id: 'bioluminescent',
  label: 'Bioluminescent Depths',
  css: {
    horizons: {
      'immediate': '#e07a5f',
      'this-week': '#d4a053',
      'this-month': '#81b29a',
      'this-quarter': '#3d9f94',
      'this-year': '#5b8fb9',
      'someday': '#7a6f63',
    },
    bgPrimary: '#0d0b08',
    bgSecondary: '#16120e',
    bgSurface: '#1e1914',
    textPrimary: '#ede6db',
    textSecondary: '#9c8e7c',
    textMuted: '#6b5e50',
    accentGlow: '#d4a053',
    accentSuccess: '#81b29a',
    accentRefinement: '#7eb8b0',
    accentDrift: '#c97c5d',
    tags: {
      work: '#5b8fb9',
      personal: '#d4a053',
      health: '#81b29a',
      finance: '#a07cc9',
      home: '#c97c5d',
      social: '#c97898',
    },
    borderRadius: 12,
    borderRadiusLarge: 16,
    backdropBlur: 8,
    surfaceOpacity: 0.8,
  },
  scene: {
    background: '#0d0b08',
    fogColor: '#1a1510',
    fogDensity: 0.015,
    ambientIntensity: 0.15,
    directionalLight: null,
    stars: { count: 300, radius: 200, depth: 100, factor: 2 },
    bloom: {
      intensity: 1.8,
      luminanceThreshold: 0.15,
      luminanceSmoothing: 0.015,
      mipmapBlur: true,
    },
    lodStrategy: 'horizon-split',
    cardHorizons: ['immediate', 'this-week'],
    sprite: {
      baseRadius: 0.3,
      emissiveMultiplier: 1.5,
      opacity: 0.9,
      defaultColor: '#8b7b6b',
      etherealTarget: '#c8bfb0',
      deadlineRingColor: '#d4a053',
      refinementRingColor: '#7eb8b0',
    },
    htmlDistanceFactor: 10,
    burstColors: {
      r: [0.83, 0.93],
      g: [0.63, 0.90],
      b: [0.33, 0.86],
    },
    inkWeight: null,
    paperTexture: false,
  },
};
